apiVersion: batch/v1
kind: CronJob
metadata:
  name: jirimodels-offer-stock-updater
  labels:
    app: jirimodels-offer-stock-updater
spec:
  schedule: "30 0 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      activeDeadlineSeconds: 600
      backoffLimit: 2
      template:
        metadata:
          labels:
            app: jirimodels-offer-stock-updater
        spec:
          imagePullSecrets:
          - name: registry-secret
          restartPolicy: OnFailure
          containers:
          - name: jirimodels-offer-stock-updater
            image: zot.jo6r.xyz/kaufland/jirimodels-offer-stock-updater:1.3
            imagePullPolicy: IfNotPresent
            command: ["python", "main.py"]
            envFrom:
                - configMapRef: 
                    name: jirimodels-offer-stock-updater
                - configMapRef:
                    name: kaufland-api
                - secretRef:
                    name: kaufland-api-secret
            resources:
              requests:
                memory: "256Mi"
                cpu: "200m"
              limits:
                memory: "1Gi"
                cpu: "1000m"