apiVersion: batch/v1
kind: CronJob
metadata:
  name: jiri-models-stock-updater
  labels:
    app: jiri-models-stock-updater
spec:
  # At 00:30.
  schedule: "30 0 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      activeDeadlineSeconds: 600
      backoffLimit: 2
      template:
        metadata:
          labels:
            app: jiri-models-stock-updater
        spec:
          imagePullSecrets:
          - name: registry-secret
          restartPolicy: OnFailure
          containers:
          - name: updater
            image: zot.jo6r.xyz/jiri-models-stock-updater:1.1
            imagePullPolicy: Always
            command: ["python", "main.py"]
            env:
            - name: DB_DSN
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: dsn
            - name: KAUFLAND_CLIENT_KEY
              valueFrom:
                secretKeyRef:
                  name: kaufland-api-secret
                  key: CLIENT_KEY
            - name: KAUFLAND_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: kaufland-api-secret
                  key: SECRET_KEY
            - name: KAUFLAND_STOREFRONT
              valueFrom:
                configMapKeyRef:
                  name: kaufland-api
                  key: storefront
            - name: KAUFLAND_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: kaufland-api
                  key: base-url
            resources:
              requests:
                memory: "256Mi"
                cpu: "200m"
              limits:
                memory: "1Gi"
                cpu: "1000m"
