apiVersion: batch/v1
kind: CronJob
metadata:
  name: shoptet-offer-stock-updater
  labels:
    app: shoptet-offer-stock-updater
spec:
  # Schedule: At minute 0 past every 2nd hour.
  schedule: "0 */2 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      activeDeadlineSeconds: 1200
      backoffLimit: 2
      template:
        metadata:
          labels:
            app: shoptet-offer-stock-updater
        spec:
          imagePullSecrets:
          - name: registry-secret
          restartPolicy: OnFailure
          containers:
          - name: shoptet-offer-stock-updater
            image: zot.jo6r.xyz/kaufland/shoptet-offer-stock-updater:1.1
            imagePullPolicy: IfNotPresent
            command: ["python", "main.py"]
            envFrom:
                - configMapRef: 
                    name: shoptet-offer-stock-updater
                - configMapRef:
                    name: kaufland-api
                - secretRef:
                    name: kaufland-api-secret
            # env:
            # - name: SHOPTET_CSV_URL
            #   valueFrom:
            #     configMapKeyRef:
            #       name: shoptet-offer-stock-updater
            #       key: SHOPTET_CSV_URL
            resources:
              requests:
                memory: "256Mi"
                cpu: "200m"
              limits:
                memory: "1Gi"
                cpu: "1000m"
